<a href="https://colab.research.google.com/github/kskmtsmr-sudo/python-practice/blob/main/2025081101.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

A.ベクトルの基本操作

In [3]:
np.arange(1,6)

array([1, 2, 3, 4, 5])

In [4]:
np.arange(1,6)*2

array([ 2,  4,  6,  8, 10])

In [5]:
v1 = np.arange(1,4)
v2 = np.arange(4,7)

In [12]:
print(v1+v2)
print(v1-v2)

[5 7 9]
[-3 -3 -3]


In [15]:
v = np.array([3,-1,2])
v

array([ 3, -1,  2])

In [16]:
v * 3

array([ 9, -3,  6])

B.内積・外積・ノルム

In [25]:
v1 = np.array([1,2,3])
v2 = np.array([-1,0,4])
print(v1*v2)
print(np.dot(v1,v2))

[-1  0 12]
11


In [18]:
v1 = np.array([1,0,0])
v2 = np.array([0,1,0])
cross = np.cross(v1,v2)
print(cross)

[0 0 1]


In [30]:
v = [3,4]
L2 = np.sqrt(v[0]**2+v[1]**2)
print(L2)
print(np.linalg.norm(v))

5.0
5.0


C.行列の基本操作

In [40]:
v2 = np.arange(1,10).reshape(3,3)

In [41]:
v2.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [47]:
v2 = np.arange(1,10).reshape(3,3)
v2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [48]:
v3 = np.arange(2,11).reshape(3,3)
v3

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [49]:
v2+v3

array([[ 3,  5,  7],
       [ 9, 11, 13],
       [15, 17, 19]])

In [50]:
v2-v3

array([[-1, -1, -1],
       [-1, -1, -1],
       [-1, -1, -1]])

D. 行列の積・単位行列   

In [54]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
print(A)
print(B)

np.matmul(A,B)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


array([[19, 22],
       [43, 50]])

In [62]:
I = np.identity(2)
I

array([[1., 0.],
       [0., 1.]])

In [78]:
print(A)
AA = np.matmul(A,I)
AA

[[2 0]
 [0 3]]


array([[2., 0.],
       [0., 3.]])

E.逆行列・連立方程式

In [67]:
A = np.array([[4,7],[2,6]])
A

array([[4, 7],
       [2, 6]])

In [66]:
np.linalg.inv(A)

array([[ 0.6, -0.7],
       [-0.2,  0.4]])

2*x + y == 5、
x + 3*y == 8

In [71]:
A = np.array([[2,1],[1,3]])
A

array([[2, 1],
       [1, 3]])

In [74]:
A_inv = np.linalg.inv(A)
A_inv

array([[ 0.6, -0.2],
       [-0.2,  0.4]])

In [79]:
b = np.array([5, 8])
x = A_inv @ b
print(x)

[1.4 2.2]


F,固有値・固有ベクトル

A = [[2, 0], [0, 3]] の固有値と固有ベクトルを求める

In [76]:
A = np.array([[2,0],[0,3]])
A

array([[2, 0],
       [0, 3]])

固有値λ、固有ベクトルx(!=0)、単位行列E
Ax = λEx
[[2,0]        [[1,0]
 [0,3]] x = λ [0,1]] x
(A-λE)x = 0
x = (A-λE)**-1 * 0 = 0
⇒ det(A-λE) = 0
[[2-λ,0]
det( [0,3-λ]]) = 0
((2-λ)*(3-λ)-0*0)=λ**2-5λ+6 = 0
(λ-3)*(λ-2)=0
λ=2,3

i,λ=2
(A-λE)x=0
x =(a、b)
[[2-λ,0]
[0,3-λ]][a,b]=0
[0,0]
[0,1][a,b]= 0


In [82]:
vals, vecs = np.linalg.eig(A)
print("固有値：", vals)
print("固有ベクトル：\n", vecs)

固有値： [2. 3.]
固有ベクトル：
 [[1. 0.]
 [0. 1.]]
