<a href="https://colab.research.google.com/github/kskmtsmr-sudo/python-practice/blob/main/20250818.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [38]:
import numpy as np
def arange_square_matrix(n):
    return np.array([np.arange(i, i+n) for i in range(n)])

In [40]:
print(all(map(all,(arange_square_matrix(3) == np.array([[0,1,2],[1,2,3],[2,3,4]])))))

True


array([0, 1, 2])

In [23]:
np.arange(1,4)

array([1, 2, 3])

In [24]:
np.arange(1,4,0.5)

array([1. , 1.5, 2. , 2.5, 3. , 3.5])

In [25]:
np.array([1,3,5])

array([1, 3, 5])

In [26]:
print(np.array([1,3,5]))

[1 3 5]


In [27]:
print(np.arange(1,4))

[1 2 3]


In [46]:
a = np.arange(10)
print(a[-2:-8:-2])

[8 6 4]


pandaライブラリ

In [2]:
import pandas as pd
import numpy as np

In [4]:
s1 = pd.Series([0,1,2])
print(s1)
s2 = pd.Series(np.random.rand(3))
print(s2)
s3 = pd.Series({0:'boo',1:'foo',2:'woo'})
print(s3)

0    0
1    1
2    2
dtype: int64
0    0.143353
1    0.944669
2    0.521848
dtype: float64
0    boo
1    foo
2    woo
dtype: object


In [5]:
d1 = pd.DataFrame([[0,1,2],[3,4,5],[6,7,8],[9,10,11]], index=[10,11,12,13], columns=['c1','c2','c3'])
print(d1)

    c1  c2  c3
10   0   1   2
11   3   4   5
12   6   7   8
13   9  10  11


In [6]:
d2 = pd.DataFrame(np.random.rand(12).reshape(4,3), columns=['c1','c2','c3'])
print(d2)

         c1        c2        c3
0  0.414662  0.264556  0.774234
1  0.456150  0.568434  0.018790
2  0.617635  0.612096  0.616934
3  0.943748  0.681820  0.359508


In [7]:
d3 = pd.DataFrame({'Initial':['B','F','W'], 'Name':['boo', 'foo', 'woo']}, columns=['Name','Initial'])
print(d3)

  Name Initial
0  boo       B
1  foo       F
2  woo       W


In [9]:
iris_d = pd.read_csv('iris.csv')
iris_d.head(10)

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa
5           5.4          3.9           1.7          0.4  setosa
6           4.6          3.4           1.4          0.3  setosa
7           5.0          3.4           1.5          0.2  setosa
8           4.4          2.9           1.4          0.2  setosa
9           4.9          3.1           1.5          0.1  setosa

In [11]:
print(iris_d.index)
len(iris_d.index)

RangeIndex(start=0, stop=150, step=1)


150

In [12]:
iris_d[:5]

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [17]:
iris_d[::-1]

sepal_length  sepal_width  petal_length  petal_width    species
149           5.9          3.0           5.1          1.8  virginica
148           6.2          3.4           5.4          2.3  virginica
147           6.5          3.0           5.2          2.0  virginica
146           6.3          2.5           5.0          1.9  virginica
145           6.7          3.0           5.2          2.3  virginica
..            ...          ...           ...          ...        ...
4             5.0          3.6           1.4          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
0             5.1          3.5           1.4          0.2     setosa

[150 rows x 5 columns]

In [19]:
iris_d.species.head(10)

0    setosa
1    setosa
2    setosa
3    setosa
4    setosa
5    setosa
6    setosa
7    setosa
8    setosa
9    setosa
Name: species, dtype: object

In [22]:
iris_d[['sepal_length','species']].head(10)

sepal_length species
0           5.1  setosa
1           4.9  setosa
2           4.7  setosa
3           4.6  setosa
4           5.0  setosa
5           5.4  setosa
6           4.6  setosa
7           5.0  setosa
8           4.4  setosa
9           4.9  setosa

In [23]:
iris_d.iloc[1]

sepal_length       4.9
sepal_width        3.0
petal_length       1.4
petal_width        0.2
species         setosa
Name: 1, dtype: object

In [24]:
iris_d.iloc[1,1]

np.float64(3.0)

In [25]:
iris_d.iloc[0:5,0:2]

sepal_length  sepal_width
0           5.1          3.5
1           4.9          3.0
2           4.7          3.2
3           4.6          3.1
4           5.0          3.6

In [26]:
iris_d.loc[5]

sepal_length       5.4
sepal_width        3.9
petal_length       1.7
petal_width        0.4
species         setosa
Name: 5, dtype: object

In [27]:
iris_d.loc[5,'sepal_length']

np.float64(5.4)

In [28]:
iris_d.loc[1:5,['sepal_length','species']]

sepal_length species
1           4.9  setosa
2           4.7  setosa
3           4.6  setosa
4           5.0  setosa
5           5.4  setosa

In [29]:
iris_d[(iris_d['sepal_length'] > 7.0) & (iris_d['sepal_width'] < 3.0)]

sepal_length  sepal_width  petal_length  petal_width    species
107           7.3          2.9           6.3          1.8  virginica
118           7.7          2.6           6.9          2.3  virginica
122           7.7          2.8           6.7          2.0  virginica
130           7.4          2.8           6.1          1.9  virginica

In [30]:
iris_d['mycolumn']=np.random.rand(len(iris_d.index))
iris_d.head(10)

sepal_length  sepal_width  petal_length  petal_width species  mycolumn
0           5.1          3.5           1.4          0.2  setosa  0.437032
1           4.9          3.0           1.4          0.2  setosa  0.697631
2           4.7          3.2           1.3          0.2  setosa  0.060225
3           4.6          3.1           1.5          0.2  setosa  0.666767
4           5.0          3.6           1.4          0.2  setosa  0.670638
5           5.4          3.9           1.7          0.4  setosa  0.210383
6           4.6          3.4           1.4          0.3  setosa  0.128926
7           5.0          3.4           1.5          0.2  setosa  0.315428
8           4.4          2.9           1.4          0.2  setosa  0.363711
9           4.9          3.1           1.5          0.1  setosa  0.570197

In [31]:
del iris_d['mycolumn']
iris_d.head(10)

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa
5           5.4          3.9           1.7          0.4  setosa
6           4.6          3.4           1.4          0.3  setosa
7           5.0          3.4           1.5          0.2  setosa
8           4.4          2.9           1.4          0.2  setosa
9           4.9          3.1           1.5          0.1  setosa

In [32]:
myiris1 = iris_d.assign(mycolumn=np.random.rand(len(iris_d.index)))
myiris1.head(5)

sepal_length  sepal_width  petal_length  petal_width species  mycolumn
0           5.1          3.5           1.4          0.2  setosa  0.209844
1           4.9          3.0           1.4          0.2  setosa  0.186193
2           4.7          3.2           1.3          0.2  setosa  0.944372
3           4.6          3.1           1.5          0.2  setosa  0.739551
4           5.0          3.6           1.4          0.2  setosa  0.490459

In [33]:
myiris2 = myiris1.drop('mycolumn', axis=1)
myiris2.head(5)

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [34]:
row = pd.DataFrame([[1,1,1,1,'setosa']], columns=iris_d.columns)

myiris4 = pd.concat([iris_d, row], ignore_index=True)
myiris4[-2:]

sepal_length  sepal_width  petal_length  petal_width    species
149           5.9          3.0           5.1          1.8  virginica
150           1.0          1.0           1.0          1.0     setosa

In [35]:
myiris4 = myiris4.drop(150)
myiris4[-2:]

sepal_length  sepal_width  petal_length  petal_width    species
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

In [36]:
sorted_iris = iris_d.sort_values(['sepal_length', 'sepal_width', 'petal_length', 'petal_width'])
sorted_iris.head(10)

sepal_length  sepal_width  petal_length  petal_width species
13           4.3          3.0           1.1          0.1  setosa
8            4.4          2.9           1.4          0.2  setosa
38           4.4          3.0           1.3          0.2  setosa
42           4.4          3.2           1.3          0.2  setosa
41           4.5          2.3           1.3          0.3  setosa
3            4.6          3.1           1.5          0.2  setosa
47           4.6          3.2           1.4          0.2  setosa
6            4.6          3.4           1.4          0.3  setosa
22           4.6          3.6           1.0          0.2  setosa
2            4.7          3.2           1.3          0.2  setosa

In [37]:
# iris_dデータフレームの4つ列の値に基づいて降順にソート
sorted_iris = iris_d.sort_values(['sepal_length', 'sepal_width', 'petal_length', 'petal_width'],ascending=False)
sorted_iris.head(10)


sepal_length  sepal_width  petal_length  petal_width    species
131           7.9          3.8           6.4          2.0  virginica
117           7.7          3.8           6.7          2.2  virginica
135           7.7          3.0           6.1          2.3  virginica
122           7.7          2.8           6.7          2.0  virginica
118           7.7          2.6           6.9          2.3  virginica
105           7.6          3.0           6.6          2.1  virginica
130           7.4          2.8           6.1          1.9  virginica
107           7.3          2.9           6.3          1.8  virginica
109           7.2          3.6           6.1          2.5  virginica
125           7.2          3.2           6.0          1.8  virginica

In [38]:
iris_d.describe()

sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.054000      3.758667     1.198667
std        0.828066     0.433594      1.764420     0.763161
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [40]:
concat_iris = pd.concat([iris_d[:5],iris_d[-5:]])
concat_iris

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

In [41]:
sepal_len = pd.concat([iris_d.loc[:, ['sepal_length']],iris_d.loc[:, ['species']]], axis=1)
sepal_len.head(10)

sepal_length species
0           5.1  setosa
1           4.9  setosa
2           4.7  setosa
3           4.6  setosa
4           5.0  setosa
5           5.4  setosa
6           4.6  setosa
7           5.0  setosa
8           4.4  setosa
9           4.9  setosa

In [45]:
# 'sepal_length'と'species'列からなる3行のデータ
sepal_len = pd.concat([iris_d.loc[[0,51,101],['sepal_length']],iris_d.loc[[0,51,101], ['species']]], axis=1)
# 'sepal_width'と'species'列からなる3行のデータ
sepal_wid = pd.concat([iris_d.loc[[0,51,101],['sepal_width']],iris_d.loc[[0,51,101], ['species']]], axis=1)

# sepal_lenとsepal_widを'species'をキーにして結合
sepal = pd.merge(sepal_len, sepal_wid, on='species')
sepal

sepal_length     species  sepal_width
0           5.1      setosa          3.5
1           6.4  versicolor          3.2
2           5.8   virginica          2.7

In [46]:
iris_d.groupby('species')

In [47]:
iris_d.groupby('species').head(5)

sepal_length  sepal_width  petal_length  petal_width     species
0             5.1          3.5           1.4          0.2      setosa
1             4.9          3.0           1.4          0.2      setosa
2             4.7          3.2           1.3          0.2      setosa
3             4.6          3.1           1.5          0.2      setosa
4             5.0          3.6           1.4          0.2      setosa
50            7.0          3.2           4.7          1.4  versicolor
51            6.4          3.2           4.5          1.5  versicolor
52            6.9          3.1           4.9          1.5  versicolor
53            5.5          2.3           4.0          1.3  versicolor
54            6.5          2.8           4.6          1.5  versicolor
100           6.3          3.3           6.0          2.5   virginica
101           5.8          2.7           5.1          1.9   virginica
102           7.1          3.0           5.9          2.1   virginica
103           6.3          2.9           5.6          1.8   virginica
104           6.5          3.0           5.8          2.2   virginica

In [49]:
iris_d.groupby('species')[['sepal_length','sepal_width']].mean()

sepal_length  sepal_width
species                              
setosa             5.006        3.418
versicolor         5.936        2.770
virginica          6.588        2.974