<a href="https://colab.research.google.com/github/kskmtsmr-sudo/python-practice/blob/main/20250810.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import numpy as np
a = np.array([1,2,3])
b = np.array((4,5,6))

In [7]:
print(a)
print(b)

[1 2 3]
[4 5 6]


In [8]:
a

array([1, 2, 3])

In [9]:
type(a)

numpy.ndarray

In [10]:
type([1,2,3])

list

In [11]:
print(np.array([-1,0,1], dtype=np.int32))

[-1  0  1]


In [13]:
print(np.array([-1,0,1], dtype=np.float64))

[-1.  0.  1.]


In [15]:
print(np.array([-1,0,1], dtype=np.complex128))

[-1.+0.j  0.+0.j  1.+0.j]


In [16]:
print(np.array([-1,0,1], dtype=np.bool_))

[ True False  True]


In [18]:
print(np.array([[1,2],[3,4]]))

[[1 2]
 [3 4]]


In [19]:
print(np.array([[[1,2],[3,4]],[[5,6],[7,8]]]))

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [27]:
a1 = np.array([1,2,3,4,5,6])
a2 = a1.reshape(2,3)

In [21]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [22]:
a1[1] = 6

In [23]:
a2

array([[1, 6, 3],
       [4, 5, 6]])

In [24]:
print(a2)

[[1 6 3]
 [4 5 6]]


In [25]:
elems = np.array([0,1,2,3,4,5])
a = elems.reshape(2,3).ravel()
elems[1] = 6
print(a)

[0 6 2 3 4 5]


In [28]:
a2.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [29]:
a2.dtype

dtype('int64')

In [30]:
a2.shape

(2, 3)

In [31]:
a2.ndim

2

In [32]:
a2.size

6

In [36]:
print(a2.flat)

In [35]:
a2.ravel

<function ndarray.ravel>

In [40]:
print(np.arange(3))
print(np.arange(0,1,0.2))

[0 1 2]
[0.  0.2 0.4 0.6 0.8]


In [41]:
print(np.linspace(0,1,4))

[0.         0.33333333 0.66666667 1.        ]


In [44]:
print(np.zeros(4))
print(np.zeros((2,3)))
print(np.ones(4))
print(np.ones((2,3)))

[0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]]
[1. 1. 1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]]


In [45]:
print(np.random.rand(4))
print(np.random.rand(2,3))

[0.61234136 0.19544623 0.08496883 0.77915275]
[[0.93140487 0.09293088 0.89986725]
 [0.75937476 0.18286522 0.46222074]]


In [55]:
def arange_square_matrix(n):
    return np.array([np.arange(i,i+n) for i in range(n)])

In [56]:
print(all(map(all,(arange_square_matrix(3) == np.array([[0,1,2],[1,2,3],[2,3,4]])))))

True


In [58]:
print(arange_square_matrix(5))

[[0 1 2 3 4]
 [1 2 3 4 5]
 [2 3 4 5 6]
 [3 4 5 6 7]
 [4 5 6 7 8]]


In [60]:
np.arange(5)[:, None]

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [61]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [62]:
x = np.arange(3)        # shape: (3,)
y = np.arange(3)[:,None]# shape: (3,1)


In [63]:
x

array([0, 1, 2])

In [65]:
y

array([[0],
       [1],
       [2]])

In [66]:
(y+x).shape

(3, 3)

In [67]:
y+x

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [73]:
a = np.arange(3)
print(a)

[0 1 2]


In [69]:
a[0]

np.int64(0)

In [70]:
a[-1]

np.int64(2)

In [74]:
a[-1] = 3

In [75]:
print(a)

[0 1 3]


In [76]:
a = np.arange(6).reshape(2,3)
print(a)

[[0 1 2]
 [3 4 5]]


In [77]:
a[1,2]

np.int64(5)

In [78]:
a[1,2] = 6

In [79]:
print(a)

[[0 1 2]
 [3 4 6]]


In [80]:
a = np.arange(5)
print(a)
print(a[1:4])
print(a[1:])
print(a[:-2])
print(a[::2])
print(a[::-1])

[0 1 2 3 4]
[1 2 3]
[1 2 3 4]
[0 1 2]
[0 2 4]
[4 3 2 1 0]


In [81]:
a = np.arange(5)
print(a)
a[1:4] = 6
print(a)
a = np.arange(5)
a[::2] = 6
print(a)

[0 1 2 3 4]
[0 6 6 6 4]
[6 1 6 3 6]


In [85]:
for idx, e in np.ndenumerate(np.arange(6).reshape(2,3)):
    print(idx,e)

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5


In [1]:
def reverse_lookup(list1):
    dic1 = {}
    for i in list1:
      dic1[i] = list1.index(i)
    return dic1

In [2]:
print(reverse_lookup(['apple', 'pen', 'orange']) == {'apple': 0, 'orange': 2, 'pen': 1})

True


In [5]:
def reverse_lookup(list1):
    return {i: list1.index(i) for i in list1}

In [6]:
print(reverse_lookup(['apple', 'pen', 'orange']) == {'apple': 0, 'orange': 2, 'pen': 1})

True


In [8]:
print(reverse_lookup(['apple', 'pen', 'orange']) == {'apple': 0, 'orange': 2, 'pen': 1})

False


In [15]:
def handle_collision(dic1, str1):
    if len(str1) not in dic1:
        dic1[len(str1)] = [str1]
        return dic1
    else:
        dic1[len(str1)] += [str1]
        return dic1

In [16]:
dic1_orig = {3: ['ham', 'egg'], 6: ['coffee', 'brandy'], 9: ['port wine'], 15: ['curried chicken']}
dic1_result = {3: ['ham', 'egg', 'tea'], 6: ['coffee', 'brandy'], 9: ['port wine'], 15: ['curried chicken']}
handle_collision(dic1_orig, 'tea')
print(dic1_orig == dic1_result)

True


In [18]:
def handle_collision(dic1, str1):
    if dic1.get(len(str1)) is None:
        ls = [str1]
    else:
        ls = dic1[len(str1)]
        ls.append(str1)
    dic1[len(str1)] = ls

In [19]:
dic1_orig = {3: ['ham', 'egg'], 6: ['coffee', 'brandy'], 9: ['port wine'], 15: ['curried chicken']}
dic1_result = {3: ['ham', 'egg', 'tea'], 6: ['coffee', 'brandy'], 9: ['port wine'], 15: ['curried chicken']}
handle_collision(dic1_orig, 'tea')
print(dic1_orig == dic1_result)

True


In [34]:
def last_line(name):
    with open(name, 'r') as f:
        for i in f.readlines():
          last = i
    print(last)
    return last

In [6]:
from google.colab import files
uploaded = files.upload()

Saving sample.txt to sample.txt


In [38]:
print(last_line('sample.txt')=="Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.\n")

Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

True


In [39]:
def last_line(name):
    with open(name, 'r') as f:
        for i in name:
          last = i
    print(last)
    return last

In [43]:
print(last_line('sample.txt')=="Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.\n")

t
False


In [46]:
def  number_of_characters(name):
    f = open(name, 'r')
    i = len(f.read())
    f.close()
    return i

In [47]:
print(number_of_characters('sample.txt') == 446)

True


In [1]:
with open('print-test.txt', 'w') as f:
    print('hello\nworld', file=f)

In [2]:
with open('print-test.txt', 'a') as f:
    print('hello', 'world\n', end='', file=f)

In [3]:
with open('print-test.txt', 'a') as f:
    print('hello', 'world', sep=', ', file=f) # 'hello, world'が印字される

In [7]:
with open('sample.txt') as src, open('sample.txt.bak', 'w') as dst:
    dst.write(src.read())

In [21]:
def file_upper(infile,outfile):
    with open(infile, 'r')  as src:
        with open(outfile, 'w') as dst:
            dst.write(src.read().upper())

In [22]:
with open('print-test.txt', 'w') as f:
    print('hello', 'world', file=f)
file_upper('print-test.txt', 'print-test-upper.txt')
with open('print-test-upper.txt', 'r') as f:
    print(f.read() == 'HELLO WORLD\n')

True


In [1]:
from google.colab import files
uploaded = files.upload()

Saving sample.txt to sample.txt


In [2]:
lines = []
with open('sample.txt', 'r') as f:
      for line in f:
        lines.append(line)
lines

['Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.\n',
 'Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.\n',
 'Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.\n']

In [4]:
with open('sample.txt', 'r') as f:
    print('最初')
    for line in f:
        print(line)
    print('もう一度')
    for line in f:
        print(line)
    print('最初に戻る')
    f.seek(0)
    for line in f:
        print(line)

最初
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.

Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.

Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

もう一度
最初に戻る
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.

Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.

Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.



In [5]:
def last_line(name):
    last = ''
    with open(name, 'r') as f:
        for line in f.readlines():
          last = line
    return last

In [6]:
assert last_line('sample.txt') == 'Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.\n'

In [13]:
def last_line(name):
    last = ''
    with open(name, 'r', encoding='utf-8') as f:
        for line in f:
            last = line
    return last

In [14]:
assert last_line('sample.txt') == 'Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.\n'

In [15]:
def but_first(ls):
    it = iter(ls)
    next(it)
    return it

In [16]:
it = but_first([0,2,4,6,8])
assert type(it) == type(iter([])) # type(it) では it は消費されない
assert list(it) == [2,4,6,8]

In [20]:
f = open('sample.txt', 'r')
next(f)

'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.\n'

In [21]:
next(f)

'Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.\n'

In [24]:
next(f)

StopIteration: 

In [25]:
f.close()

In [26]:
it = enumerate([10,20,30])

In [27]:
next(it)

(0, 10)

In [28]:
for x in it:
    print(x)

(1, 20)
(2, 30)


In [29]:
for i, c in enumerate('ABCD'):
    print(i,c)

0 A
1 B
2 C
3 D


In [30]:
with open('sample.txt', 'r') as f:
    for i, s in enumerate(f):
        print(i, '行目')
        print(s)

0 行目
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.

1 行目
Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.

2 行目
Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

