In [1]:
fruits = {'apple': 3, 'banana': 5, 'orange': 2}

In [11]:
for key,value in fruits.items():
    print('「', key, 'は', value, '個」')

「 apple は 3 個」
「 banana は 5 個」
「 orange は 2 個」


In [10]:
def total_items(dic):
    total = 0
    for value in fruits.values():
        total += value
    return total

In [12]:
total_items(fruits)

10

In [16]:
for i in range(2,11,2):
    print(i)

2
4
6
8
10


In [18]:
def rank(score):
    if score >= 80:
      return "優"
    elif score >= 60:
      return "良"
    else :
      return "可"

In [23]:
rank(59)

'可'

In [33]:
def join_numbers(nums):
    str1 = ''
    for i in len(nums):

    return str1

In [34]:
join_numbers([1,2,3])

TypeError: can only concatenate str (not "int") to str

In [31]:
def first_chars(words):
    str1 = ''
    for i in words:
        str1 = str1 + i[0:1]
    return str1

In [30]:
words = ['Python', 'is', 'great']

In [32]:
first_chars(words)

'Pig'

In [38]:
def join_even_numbers(nums):
    result = ''
    for i in nums:
        if i%2 == 0:
            result +=  ''.join(str(i))
    return result

In [13]:
  def last_line(name):
      last = ''
      line = ''
      with open(name, 'r') as f:
          while True:
            line = f.readline()
            if line == '':
                return last
            else:
                last = line

In [15]:
def last_line(name):
    last = ''
    with open(name, ' r') as f:
        for line in f:
            last = line
    return last.strip()


In [12]:
from google.colab import files
uploaded = files.upload()


KeyboardInterrupt: 

In [ ]:
  def last_line(name):
      last = ''
      f = open(name, 'r')
      while True:
        last = f.readline()
        if last == '':
            return last

In [19]:
def  number_of_characters(name):
    with open(name, 'r') as f:
        return len(f.read())

In [20]:
number_of_characters('sample.txt')

47

In [ ]:
def file_upper(infile,outfile):
    with open(infile, 'r') as src, open(outfile, 'w') as dsn:
        src_upper = src.read(infile).upper()
        dsn.write(src_upper)


In [22]:
lines = []
with open('sample.txt', 'r') as f:
    for line in f:
        lines.append(line)
lines

['Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.\n',
 'Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.\n',
 'Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.']

In [39]:
 def last_line(name):
    last = ''
    with open(name, 'r') as f:
      for line in f:
        last = line
    return last

In [40]:
assert last_line('sample.txt') == 'Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.\n'

In [41]:
it = iter([0,1,2])

In [42]:
it = iter([0,1,2])
next(it)

0

In [43]:
next(it)

1

In [44]:
next(it)

2

In [45]:
next(it)

StopIteration: 

In [47]:
for x in [0,1,2]:
  print(x)

0
1
2


In [50]:
try:
  it = iter([0,1,2])
  while True:
      x = next(it)
      print(x)
except StopIteration:
    pass

0
1
2


In [52]:
it = iter([0,1,2])
for x in it:
    print(x)

0
1
2


In [54]:
for x in it:
    print('これは実行されない')

In [55]:
it = iter([0,1,2])
it is iter(it)

True

In [60]:
def but_first(ls):
    it = iter(ls)
    next(it)
    return it

In [61]:
it = but_first([0,2,4,6,8])
assert type(it) == type(iter([])) # type(it) では it は消費されない
assert list(it) == [2,4,6,8]

In [62]:
f = open('sample.txt', 'r')

In [63]:
next(f)

'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.\n'

In [64]:
next(f)

'Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.\n'

In [65]:
next(f)

'Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.\n'

In [66]:
next(f)

StopIteration: 

In [67]:
f.close()

In [68]:
it = enumerate([10,20,30])

In [69]:
next(it)

(0, 10)

In [70]:
for x in it:
    print(x)

(1, 20)
(2, 30)


In [2]:
for i, c in enumerate('ACBD'):
    print(i, '番目の文字 =', c)

0 番目の文字 = A
1 番目の文字 = C
2 番目の文字 = B
3 番目の文字 = D


In [3]:
    for i, s in enumerate(f):
      print(i,'行目：')
      print(s)

FileNotFoundError: [Errno 2] No such file or directory: 'sample.txt'

In [4]:
from google.colab import files
uploaded = files.upload()

Saving sample.txt to sample.txt


In [5]:
open('sample.txt', 'r', encoding='utf-8')

<_io.TextIOWrapper name='sample.txt' mode='r' encoding='utf-8'>

In [6]:
open('novel.txt', 'r')

FileNotFoundError: [Errno 2] No such file or directory: 'novel.txt'

In [9]:
pi = 'パイ' # piという変数に文字列「パイ」を代入する
print(pi)
from math import pi
print(pi) # mathモジュールのpiの値で上書きされる（衝突）

パイ
3.141592653589793


In [10]:
from math import sqrt
from math import sin
from math import pi

print(sqrt(2))
print(sin(pi))

1.4142135623730951
1.2246467991473532e-16


In [12]:
import sys
if 'google.colab' in sys.modules:
    from google.colab import files
    uploaded = files.upload()

Saving 20250807.py to 20250807.py


In [13]:
import numpy as np

In [14]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [15]:
b = np.array((1,2,3))
print(b)

[1 2 3]


In [16]:
a

array([1, 2, 3])

In [17]:
b

array([1, 2, 3])

In [19]:
type(np.array([1,2,3,4,5]))

numpy.ndarray

In [20]:
type([1,2,3,4,5])

list

In [25]:
def reverse_lookup(list1):
    dic1 = {}
    for i in list1:
      dic1[i] = list1.index(i)
    return dic1

In [26]:
print(reverse_lookup(['apple', 'pen', 'orange']) == {'apple': 0, 'orange': 2, 'pen': 1})


True


In [35]:
def handle_collision(dic1, str1):
    n = len(str1)
    if n not in dic1:
		    dic1[n] = [str1]
    else:
		    dic1[n].append(str1)
    return dic1

In [36]:
dic1_orig = {3: ['ham', 'egg'], 6: ['coffee', 'brandy'], 9: ['port wine'], 15: ['curried chicken']}
dic1_result = {3: ['ham', 'egg', 'tea'], 6: ['coffee', 'brandy'], 9: ['port wine'], 15: ['curried chicken']}
handle_collision(dic1_orig, 'tea')
print(dic1_orig == dic1_result)

True


In [37]:
def exception3(x,y,z):
		if x == y:
				return z
		elif y == z:
				return x
		else:
				return y

In [38]:
print(exception3(1,2,2))
print(exception3(4,2,4))
print(exception3(9,3,9))

1
2
3


In [42]:
def exception9(a):
		x = a[0] + a[1] + a[2]
		y = a[3] + a[4] + a[5]
		z = a[6] + a[7] + a[8]
		if exception3(x,y,z) == x:
			return exception3(a[0],a[1],a[2])
		elif exception3(x,y,z) == y:
			return exception3(a[3],a[4],a[5])
		else:
			return exception3(a[6],a[7],a[8])

In [43]:
print(exception9([1,2,2,2,2,2,2,2,2]))
print(exception9([4,4,4,4,4,2,4,4,4]))
print(exception9([9,9,9,9,9,9,9,9,3]))

1
2
3
