<a href="https://colab.research.google.com/github/kskmtsmr-sudo/python-practice/blob/main/20250817.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

高階関数

In [4]:
def max_value_key(d):
    return max(d, key= lambda k: d[k])


In [5]:
print(max_value_key({3:10, 5:2, 9:1}) == 3)

True


In [8]:
def max_abs(ln):
    return max(map(abs, ln))

In [9]:
print(max_abs([3,-8,1,0,7,-5]) == 8)

True


In [ ]:
def number_of_big_numbers(ln, n):
    return sum(map(lambda x: 1, filter(lambda x: x>n, ln)))

In [11]:
def number_of_long_lines(file, n):
    with open(file, 'r', encoding='utf-8') as f:
        return  sum(map(lambda x: 1, dilter(lambda x: len(x)>n, f)))

numpy配列

In [14]:
import numpy as np
a = np.array([1,2,3])
print(a)
b = np.array((1,2,3))
print(b)

[1 2 3]
[1 2 3]


In [16]:
print(np.array([[1,2],[3,4]]))

[[1 2]
 [3 4]]


In [17]:
print(np.array([[[2,3],[3,4]],[[5,6],[7,8]]]))

[[[2 3]
  [3 4]]

 [[5 6]
  [7 8]]]


In [19]:
a1 = np.array([0,1,2,3,4,5])
a2 = a1.reshape(2,3)
a2

array([[0, 1, 2],
       [3, 4, 5]])

In [20]:
a2.ravel()

array([0, 1, 2, 3, 4, 5])

In [22]:
print(np.arange(3))
print(np.arange(0,1,0.2))

[0 1 2]
[0.  0.2 0.4 0.6 0.8]


In [24]:
print(np.linspace(0,1,3))

[0.  0.5 1. ]


In [27]:
print(np.zeros(4))
print(np.zeros((2,3)))
print(np.ones(4))
print(np.ones((2,3)))

[0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]]
[1. 1. 1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]]


In [31]:
print(np.random.randn(4))
print(np.random.randn(2,3))

[ 0.24436233  0.17623679 -0.30949397 -0.61508457]
[[-1.1053927  -0.11207726  0.49480627]
 [ 1.01035326 -0.30761945 -0.27350007]]


In [42]:
print(np.random.poisson(6,3))

[6 9 9]


In [55]:
def arange_square_matrix(n):
    return np.array([np.arange(i, n+i) for i in range(n)])

In [56]:
print(all(map(all,(arange_square_matrix(3) == np.array([[0,1,2],[1,2,3],[2,3,4]])))))

True
