In [13]:
def printfile(name):
    with open(name, 'r') as f:
      for line in f:
          print(line)

In [14]:
printfile('sample.txt')

Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.

Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.

Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.



In [42]:
def new_line(name, ln):
    with open(name, 'w') as f:
      for line in ln:
        f.write(line + '\n')

In [43]:
fruits = ['grape', 'orange']

In [45]:
new_line('output.txt', fruits)

In [46]:
open('output.txt', 'r').read()

'grape\norange\n'

In [28]:
nums = [10, 20, 30]
it = iter(nums)
print(next(it))
print(next(it))
print(next(it))
print(next(it))

10
20
30


StopIteration: 

In [49]:
def counter(n):
    it = iter(range(1, n+1))
    for _ in range(n):
        print(next(it))


In [51]:
counter(16)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16


In [39]:
from math import pi, sin, sqrt
print(pi)
print(sin(pi/2))
print(sqrt(2))

3.141592653589793
1.0
1.4142135623730951


In [41]:
import my_utils

ModuleNotFoundError: No module named 'my_utils'

In [75]:
code = """
def double(x):
    return 2 ** x
"""

with open('my_utils.py', 'w') as f:
    f.write(code)

In [76]:
from google.colab import files
files.download('my_utils.py')

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

In [80]:
import importlib
importlib.reload(my_utils)

<module 'my_utils' from '/content/my_utils.py'>

In [82]:
import my_utils as d
d.double(5)

32

In [1]:
a = [1,2,3]
b = [4,5,6]
c = [a[i] + b[i] for i in range(len(a))]

In [3]:
import numpy as np

In [4]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [5]:
b = np.array((1,2,3))

In [7]:
print(b)

[1 2 3]


In [8]:
a

array([1, 2, 3])

In [10]:
type(np.array([1,2,3,4,5]))

numpy.ndarray

In [11]:
type([1,2,3,4,5])

list

In [12]:
print(np.array([-1,0,1], dtype=np.int32))

[-1  0  1]


In [15]:
print(np.array([-1,0,1], dtype=np.float64))

[-1.  0.  1.]


In [16]:
print(np.array([-1,0,1], dtype=np.complex128))

[-1.+0.j  0.+0.j  1.+0.j]


In [18]:
print(np.array([-1,0,1], dtype=np.bool_))

[ True False  True]


In [19]:
print(np.array([[1,2],[3,4]]))

[[1 2]
 [3 4]]


In [20]:
print(np.array([[[1,2],[3,4]],[[5,6],[7,8]]]))

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [21]:
print(np.array([[1,2],[3]]))

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [28]:
a1 = np.array([0,1,2,3,4,5])
a2 = a1.reshape(2,3)
a2

array([[0, 1, 2],
       [3, 4, 5]])

In [29]:
a1[1] = 6
print(a1)
print(a2)

[0 6 2 3 4 5]
[[0 6 2]
 [3 4 5]]


In [31]:
a = np.array([0,1,2,3,4,5]).reshape(2,3)
print(a)
print(a.ravel())

[[0 1 2]
 [3 4 5]]
[0 1 2 3 4 5]


In [32]:
elems = np.array([0,1,2,3,4,5])
a = elems.reshape(2,3).ravel()
elems[1] = 6
print(a)

[0 6 2 3 4 5]


In [37]:
print(np.arange(3))
print(np.arange(0,1,0.2))

[0 1 2]
[0.  0.2 0.4 0.6 0.8]


In [6]:
import numpy as np
print(np.linspace(0,1,4))

[0.         0.33333333 0.66666667 1.        ]


In [9]:
print(np.zeros(4))
print(np.zeros((2,3)))
print(np.ones(4))
print(np.ones((2,3)))

[0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]]
[1. 1. 1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]]


In [10]:
print(np.random.rand(4))
print(np.random.rand(2,3))

[0.34727315 0.5392447  0.49370081 0.33644022]
[[0.70758306 0.87705885 0.94092956]
 [0.29555894 0.24653372 0.82657079]]


In [18]:
def arange_square_matrix(n):
    rows = [np.arange(i, i + n) for i in range(n)]
    return np.array(rows)

In [19]:
print(all(map(all,(arange_square_matrix(3) == np.array([[0,1,2],[1,2,3],[2,3,4]])))))

True


In [24]:
arange_square_matrix(5)

array([[0, 1, 2, 3, 4],
       [1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7],
       [4, 5, 6, 7, 8]])

In [25]:
a = np.arange(3)
print(a)

[0 1 2]


In [26]:
a[0]

np.int64(0)

In [27]:
a[-1]

np.int64(2)

In [29]:
a[-1] = 3
print(a)

[0 1 3]


In [30]:
a = np.arange(6).reshape(2,3)
print(a)

[[0 1 2]
 [3 4 5]]


In [31]:
a[1,2]

np.int64(5)

In [32]:
a[1,2] = 6
print(a)

[[0 1 2]
 [3 4 6]]


In [33]:
a = np.arange(5)
print(a)
print(a[1:4])
print(a[1:])
print(a[:-2])
print(a[::2])
print(a[::-1])

[0 1 2 3 4]
[1 2 3]
[1 2 3 4]
[0 1 2]
[0 2 4]
[4 3 2 1 0]


In [3]:
import numpy as np

In [4]:
a = np.arange(5)
print(a)
a[1:4] =6
print(a)
a = np.arange(5)
a[::2] = 6
print(a)

[0 1 2 3 4]
[0 6 6 6 4]
[6 1 6 3 6]


In [5]:
a = [0,1,2,3,4]
print(a)
a[1:4] = 6

[0, 1, 2, 3, 4]


TypeError: can only assign an iterable

In [6]:
a = [0,1,2,3,4]
print(a)
a[1:4] = [6]
print(a)

[0, 1, 2, 3, 4]
[0, 6, 4]


In [7]:
a = np.arange(9).reshape(3,3)
print(a)
print(a[:2,:2])
print(a[1:,1:])

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 1]
 [3 4]]
[[4 5]
 [7 8]]


In [8]:
for v in np.arange(3):
    print(v)

0
1
2


In [9]:
for row in np.arange(6).reshape(2,3):
    print(row)

[0 1 2]
[3 4 5]


In [14]:
for idx, e in np.ndenumerate(np.arange(6).reshape(2,3)):
    print(idx, e)

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5


In [15]:
for idx, e in np.ndenumerate(np.arange(3)):
    print(idx,e)

(0,) 0
(1,) 1
(2,) 2


In [16]:
a = np.arange(4)
print(a)

print(a + 1)
print(a - 1)
print(a * 2)
print(a / 2)
print(a // 2)
print(a % 2)
print(a ** 2)

print(1 + a)
print(1 -a)
print(2 * a)
b = a + 1
print(1 / b)
print(9 // b)


[0 1 2 3]
[1 2 3 4]
[-1  0  1  2]
[0 2 4 6]
[0.  0.5 1.  1.5]
[0 0 1 1]
[0 1 0 1]
[0 1 4 9]
[1 2 3 4]
[ 1  0 -1 -2]
[0 2 4 6]
[1.         0.5        0.33333333 0.25      ]
[9 4 3 2]


In [17]:
a = np.arange(4).reshape(2,2)
b = np.arange(1,5).reshape(2,2)
print(a)
print(b)
print(a + b)
print(a - b)
print(a * b)
print(a / b)
c = 3 * a
print(c // b)
print(a % b)
print(a ** b)

[[0 1]
 [2 3]]
[[1 2]
 [3 4]]
[[1 3]
 [5 7]]
[[-1 -1]
 [-1 -1]]
[[ 0  2]
 [ 6 12]]
[[0.         0.5       ]
 [0.66666667 0.75      ]]
[[0 1]
 [2 2]]
[[0 1]
 [2 3]]
[[ 0  1]
 [ 8 81]]


In [18]:
a = np.zeros(3) + 2
print(a)

[2. 2. 2.]


In [24]:
print(np.sqrt(a))
b = np.zeros((2,2)) + 2
print(b)

[1.41421356 1.41421356 1.41421356]
[[2. 2.]
 [2. 2.]]


In [25]:
print(np.sqrt(b))
print(np.sqrt(2))

[[1.41421356 1.41421356]
 [1.41421356 1.41421356]]
1.4142135623730951


In [29]:
np.dot(np.arange(4), np.arange(1,5))

np.int64(20)

In [30]:
print(np.dot(np.arange(4).reshape(2,2), np.arange(1,5).reshape(2,2)))

[[ 3  4]
 [11 16]]


In [33]:
a = np.array([3,4,-1,0,2])
print(a)
print(np.sort(a))
print(a)

[ 3  4 -1  0  2]
[-1  0  2  3  4]
[ 3  4 -1  0  2]


In [32]:
a = np.array([3,4,-1,0,2])
print(a)
a.sort()
print(a)

[ 3  4 -1  0  2]
[-1  0  2  3  4]


In [34]:
a = np.arange(6).reshape(2,3)
print(a)
print(a.sum())
print(a.sum(0))
print(a.sum(1))

[[0 1 2]
 [3 4 5]]
15
[3 5 7]
[ 3 12]


In [36]:
np.savetxt('arange3.txt', np.arange(3))

In [37]:
np.savetxt('arange2x3.txt', np.arange(6).reshape(2,3))

In [39]:
a = np.loadtxt('arange2x3.txt')
print(a)

[[0. 1. 2.]
 [3. 4. 5.]]


In [40]:
a = np.arange(6)
print(a)
print(a < 3)

[0 1 2 3 4 5]
[ True  True  True False False False]


In [48]:
a = np.array([0,1,2,-3,-4,5,-6,-7])
print(a)
print(a[a < 0])
print(a[~(a < 0) & ~(a % 2 == 0)])
a[a < 0] = 8
print(a)

[ 0  1  2 -3 -4  5 -6 -7]
[-3 -4 -6 -7]
[1 5]
[0 1 2 8 8 5 8 8]


In [53]:
I = np.identity(3)

In [54]:
print(I)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [55]:
a = np.arange(9).reshape(3,3)
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [56]:
print(np.matmul(a, I))

[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]


In [58]:
np.linalg.norm(np.ones(3))

np.float64(1.7320508075688772)